### PR TITLE
Rudementary bundling of assets with the Qt Resource System

### PR DESCRIPTION
**Pull request by MoritzMaxeiner**
Just the D side for [this](https://github.com/filcuc/DOtherSide/pull/30)

### CODE REVIEW

**Comment by filcuc** [comment]
When the DOtherSide pull is integrated, i'll also merge this one. Thank you for your work

**Comment by MoritzMaxeiner** [comment]
I will add an simple example to this PR (so don't merge it yet); for the moment a complete (integrated) example would be [the project](https://github.com/Calrama/beacon) I wrote the code in the PRs for in the first place.

**Comment by MoritzMaxeiner** [comment]
Minimal example showing how to bundle the main QML file inside of an external binary resource added. Since I have no experience in writing QML modules I did not include that. 

However, for an example on how to generate a QRC specification file for existing third-party QML modules and allow your bundled QML files to import these modules from an external binary resource, these were my steps to do just that with [Material for QtQuick](http://papyros.io/qml-material/index.html):
1. [Generate QRC file, Part 1](https://github.com/Calrama/beacon/blob/b85853a8199c659e1516c0bfc0c22713af372713/dub.sdl#L14)
2. [Generate QRC file, Part 2](https://github.com/Calrama/beacon/blob/b85853a8199c659e1516c0bfc0c22713af372713/tools/generate-qml-material-qrc)
3. [Generate external binary resource as usual](https://github.com/Calrama/beacon/blob/b85853a8199c659e1516c0bfc0c22713af372713/dub.sdl#L24)
4. [Register said resource as usual](https://github.com/Calrama/beacon/blob/b85853a8199c659e1516c0bfc0c22713af372713/src/main/d/app.d#L21)
5. [Add import path for modules leading into the Qt Resource System](https://github.com/Calrama/beacon/blob/b85853a8199c659e1516c0bfc0c22713af372713/src/main/d/app.d#L23); in this case the modules are below the directory "modules"
6. [Import modules as usual](https://github.com/Calrama/beacon/blob/b85853a8199c659e1516c0bfc0c22713af372713/src/main/qml/app.qml#L2), Qt will automatically look them up inside its Resource System, since we added an appropriate import path in the previous step

That _should_ be all that is required, though it's possible I overlooked a step when reflecting on what I did.

**Also**: Thank _you_ deeply for your work on DOtherSide and dqml, it's both exhilarating and elating to _finally_ have a way to rapidly develop beautifully-looking cross-platform GUI applications (using D). On that note something OT: DOtherSide and dqml work both fine on OS X 10.11 for me (qt5 and cmake installed via homebrew, dmd via official dmg from dlang.org).

**Comment by filcuc** [comment]
@Calrama  thank you for your kind works and that everything worked out fine. Keep in mind that both dqml and dotherside are basically in a pre alpha state. Basically they need testing with some real world project for being considered stable. Given that, if you need support for any kind of feature just ask. I'll try to do my best for implementi what you need

**Pull request merged**
