### PR TITLE
Miscellaneous

### PR DESCRIPTION
**Pull request by MoritzMaxeiner**
Companion PR to https://github.com/filcuc/DOtherSide/pull/31

### CODE REVIEW

**Comment by filcuc** [comment]
This is fine, but since it depends on the other one i'll integrate it later

**Comment by filcuc** [comment]
@Calrama  Examples fails to compile due to unknown reference to QObject in QQmlApplicationEngine

**Comment by MoritzMaxeiner** [comment]
@filcuc Welp, my bad; apparently I need to be more careful when cherry-picking.

**Comment by filcuc** [comment]
Fine thank you

**Pull request merged**
